=== MisterRatt/desktop-tutorial/proyectoweb/registrados.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:element name="registrados">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="usuario"/>
            </xs:sequence>
            <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="usuario">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="clave"/>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nombre" type="xs:NCName"/>
    <xs:element name="clave" type="xs:NCName"/>
</xs:schema>

=== MisterRatt/desktop-tutorial/proyectoweb/registrados.xml
<?xml version="1.0" encoding="utf-8"?>
<registrados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/cris_/Downloads/proyectoweb/registrados.xsd">
  <usuario id="1">
    <nombre>USR1</nombre>
    <clave>CLAVE1</clave>
  </usuario>
  <usuario id="2">
    <nombre>USR2 </nombre>
    <clave>CLAVE2</clave>
  </usuario>
  <usuario id="3">
    <nombre>USR3 </nombre>
    <clave>CLAVE3</clave>
  </usuario>
  <usuario id="4">
    <nombre>USR4</nombre>
    <clave>CLAVE4</clave>
  </usuario>
  <usuario id="5">
    <nombre>Christian</nombre>
    <clave>Garcia</clave>
  </usuario>
</registrados>
